POST http://localhost:3000/users
Content-Type: application/json


{
    "email": "dfwe@what.com",
    "firstName": "fsewdfsdfse",
    "lastName": "poindsdfdfdfsdfdt3",
    "password": "sdfsfet345!"

}
    
