POST http://localhost:3000/users
Content-Type: application/json

{
    "email": "john.seconsdfdddd@point.com",
    "firstName": "poindfdst2",
    "lastName": "poindfdt3",
    "password": "234f3dfgdsf43334f!"

}
