POST http://localhost:3000/auth/refresh-token
Content-Type: application/json



{
    "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjE3LCJlbWFpbCI6ImRmd2VAd2hhdC5jb20iLCJpYXQiOjE3NDg2MjE3MjIsImV4cCI6MTc0OTQ4NTcyMiwiYXVkIjoibG9jYWxob3N0OjMwMDAiLCJpc3MiOiJsb2NhbGhvc3Q6MzAwMCJ9.MDCMutUt4Y1_iC0FEQGwlFpGanAye6mi_TS135iMCyY"
}
