POST http://localhost:3000/auth/refresh-token
Content-Type: application/json



{
    "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjE3LCJlbWFpbCI6ImRmd2VAd2hhdC5jb20iLCJpYXQiOjE3NDg2MjI1NTMsImV4cCI6MTc0OTQ4NjU1MywiYXVkIjoibG9jYWxob3N0OjMwMDAiLCJpc3MiOiJsb2NhbGhvc3Q6MzAwMCJ9.hkFigR3quG8CMM8f5TetwaGf1-UxRRerN9ji7xYV7-M"
}
